import { Inter } from "next/font/google";
import './globals.css'
import { Metadata } from "next";
import Logo from '../../public/logo.svg'
const inter = Inter({ subsets: ["latin"] });

export const metadata:Metadata = {
  title: "Proyecto JIC 2024",
  description: "Generated by create next app",
  icons: {
    icon: Logo.src
  }
};

import React from 'react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
